### ISSUE TITLE
Units in  `pandas.DataFrame` break on vectorised functions when `default_format` is set

### ISSUE THREAD

**Issue by lukauskas** [hgrecco/pint#371] opened 2016-04-26 18:14 UTC
``` python
import pint
import pandas as pd
ureg = pint.UnitRegistry()
#ureg.default_format = '.2f~' # uncommenting this triggers the bug
x = pd.DataFrame([{'test': 5.5 * ureg.microliter, 'ing': 6.5 * ureg.microliter},
                  {'test': 7.5 * ureg.microliter, 'ing': 8.5 * ureg.milliliter}])
x.sum()
```

Works and returns

```
ing     8506.5 microliter
test      13.0 microliter
dtype: object
```

as expected.

However, if the default formatting line is uncommented, a `TypeError: non-empty format string passed to object.__format__` is raised. I am positive is due to `magnitude` becoming a `np.ndarray` instance which cannot handle the `.2f~` formatting.

I am running the following versions of the packages involved:

```
Python 3.4.3 (default, Aug 11 2015, 08:57:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
Pandas 0.18.0
Numpy 1.11.0
Pint 0.8.dev0
```

**Comment by hgrecco** [comment] 2016-04-28 21:34
Indeed that is the case: 
```python
>>> '{:.2f}'.format(np.ones(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: non-empty format string passed to object.__format__
```
I am not sure it is a bug. It is certainly annoying but it is reproducing the way Python operates. Only valid format codes for the specific object can be used. For example:
```python
>>> '{:d}'.format(2)
'2'
>>> '{:d}'.format(2.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown format code 'd' for object of type 'float'
```
I do agree that the error message could be improved.

Having said all this and because Pint uses numpy transparently, I would not object a patch that uses `array2string` if a numpy array is used.

**Comment by hgrecco** [comment] 2016-04-29 03:41
While closing #335 we implemented a something that comes very close. You might see something in this direction soon.

**Comment by hgrecco** [comment] 2019-12-03 17:47
Closing. Feel free to reopen.

**Closed by hgrecco** 2019-12-03 17:47 UTC
