### ISSUE TITLE
Special case for operation with offset unit

### ISSUE THREAD

**Issue by gdavis-github** [hgrecco/pint#248] opened 2015-03-07 03:03 UTC
> Q_(15, 'degC') + Q_(12, 'degC')
> OffsetUnitCalculusError: Ambiguous operation with offset unit (degC, degC).

There is nothing ambiguous when it is the **same** offset unit. It would be nice to avoid this error when the units are the same. Code could then convert what is considered the delta in context, rather than deal with the delta_degC object and ilk.

<i>I don't know if its related, but in lantz, if the units for a Feat is a temperature, you cannot return a float for a temperature. For most Feats units, the float will be converted to the Q_ of the units. For temperature, it throws an error. The solution is to convert to a Q_ on the return.</i>

<i>A side effect of returning a Q_ for Feat temperatures, is that the Feat doesn't work in the test GUI!</i>

<i>I'm guessing this needs to be a fix in Pint.</i>

**Comment by dalito** [comment] 2015-03-07 11:12
This is by design. What is the use case that requires adding two quantities with temperature unit degC? Often one of the summands is a delta_unit. The only exception that I can imagine is averaging multiple measurements. But in case of averaging you conceptually have an array of numbers of the same unit but not an array of quantities.

I did the overhaul of the relative units in pint 9 month ago, see #147. One of the key motivations was to raise errors in case of all ambiguous cases. My opinion is still that degC + degC is such a case.

**Comment by gdavis-github** [comment] 2015-03-07 15:48
Use cases:
* a ControlMethod that takes property min, max, step_size and setter_function for any Quantity
  * works fine on any Quantiy but temperature (or other offset unit)
  * error is raised when adjusting the setting, by adding or subtracting the step_size
  * solution is to
    * ask the user to enter deltas when the Quantity is an offset unit (unituitive special case)
    * generate a delta from a Quantity, using some pretty clumsy code (chosen)
  * meta-problem: this function was finished, until it got applied to temperature control
* lantz Feats don't work as documented in that package, when used for offset units (so it has caused a problem in another package)
* lantz GUI test does not work for offset units (ditto)

**Comment by hgrecco** [comment] 2015-03-08 00:57
I think the argumentation in #147 by @dalito is really good. It has a good balance between correctness and practicality. Even though Pint was born from Lantz, it has a larger audience. 

This is a bug in Lantz and I will solve it there. Thanks for reporting this.

**Comment by hgrecco** [comment] 2015-04-04 03:22
I am closing this right now. Feel free to reopen this in Lantz.

**Closed by hgrecco** 2015-04-04 03:22 UTC
