### ISSUE TITLE
Ordering of unit conversions produces different results

### ISSUE THREAD

**Issue by rebeccafair** [hgrecco/pint#1082] opened 2020-04-17 10:20 UTC
These two pieces of code produce slightly different unit conversions, depending on which unit conversion was called first, due to caching:

```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> x = 1*ureg('bohr').to('angstrom')
>>> y = 1*ureg('1/angstrom').to('1/bohr')
>>> print(f'{y:.16f}')
0.5291772109039775 / bohr
```

```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> y = 1*ureg('1/angstrom').to('1/bohr')
>>> print(f'{y:.16f}')
0.5291772109039772 / bohr
```

This is enough to make tests in my test suite pass/fail depending on which order they're run in.

It seems a similar issue was already discussed in #327 but it appears to have resurfaced here?

**Comment by hgrecco** [comment] 2020-04-17 13:08
This is again a problema related to floating point numbers.
Take a look at the current code:
```python
>>> from pint import UnitRegistry
>>> from decimal import Decimal
>>> ureg = UnitRegistry(non_int_type=Decimal)
>>> x = 1*ureg('bohr').to('angstrom')
>>> y = 1*ureg('1/angstrom').to('1/bohr')
>>> print(f'{y:.16f}')
0.5291772109039774 / bohr
>>> ureg2 = UnitRegistry(non_int_type=Decimal)
>>> y = 1*ureg2('1/angstrom').to('1/bohr')
>>> print(f'{y:.16f}')
0.5291772109039774 / bohr
```

**Comment by keewis** [comment] 2020-04-17 13:42
I think the issue is that the value of `y` changes if we compute something unrelated first. Is there some kind of global / per registry state that gets mutated by the computation of `x` and that doesn't affect `Decimal`?

**Comment by rebeccafair** [comment] 2020-04-17 14:34
I'm not sure if using `Decimal` is a solution, most of my variables are Numpy arrays, which doesn't recognise `Decimal`.

The issue is more as keewis said, the answer is different depending on what (seemingly unrelated) calls have been made before. Looking in the code a little more it seems the call to `ureg('bohr').to('angstrom')` causes a key `<UnitsContainer({'angstrom': -1, 'bohr': 1.0})>` to be written to `UnitRegistry._cache.root_units` which is reused on the call to `ureg('1/angstrom').to('1/bohr)`. Would it be possible to somehow disable the cache? That would be useful for consistent testing.

**Comment by hgrecco** [comment] 2020-04-17 18:01
I think it is a floating point number issue. Just picture the cache as doing the calculation in a different order

However, I think there is a good suggestion here: Provide a flag to disable the cache at construction of the `UnitRegistry`. Please bear in mind that there are multiple caches. Maybe we should ennumerate them first to see if we should provide a single flag for all, multitple flags o disable only some of them

But also, regarding your comment about numpy arrays, I think we should improve the non float experience in this case by allowing to change the dtype.

**Comment by rebeccafair** [comment] 2020-04-20 10:04
Thanks for your reply, I'm glad you agree optionally disabling the cache would be a useful feature. I would be happy to contribute to this, but it might be slightly complex for a first issue so I would probably need some help.

From looking at `registry.py` it seems the only cache that stores floats is `root_units`, (although correct me if I'm wrong). From my perspective that's the only one I would want to disable, but perhaps it is better to be more general and allow any to be disabled.

**Comment by hgrecco** [comment] 2020-04-20 15:34
Indeed there is now only one cache, but it contains many inside. My suggestion would be to disable all, but in a smart way that does not add an `if` in every single place, but rather affects the cache class

**Comment by hgrecco** [comment] 2023-04-27 05:00
I am closing this for the time being. Feel free to reopen if needed.

**Closed by hgrecco** 2023-04-27 05:00 UTC
