### ISSUE TITLE
Behavior defining quantities using strings

### ISSUE THREAD

**Issue by jsantner** [hgrecco/pint#649] opened 2018-06-25 23:35 UTC
Pint works well when defining a quantity with a string. For example
```
Q_ = pint.UnitRegistry().Quantity
test1 = Q_('50 kelvin')
test2 = Q_('1.1 m/s * kelvin ** 4')
```
But, this does not work with two cases that I've found: `nan`'s and Offset Units
```
Q_ = pint.UnitRegistry().Quantity
test1 = Q('50 degC')  # This raises OffsetUnitCalculusError.
test1 = Q('50', 'degC')  # This appears to work at first, but...
in_kelvin = test1.to('kelvin')  # ... trying to convert raises a TypeError.
test2 = Q_('nan meters')  # This raises an UndefinedUnitError
test2 = Q_(numpy.nan, 'meters')  # This works fine, and can be "converted" to numpy.nan in other units
```
I'm using version 0.8.1 on Python 3.6.

**Comment by cpascual** [comment] 2018-06-26 07:50
I can also reproduce the issues with python 2.7

Just in case this gives some hint: I noticed that first issue (`Q_('50 degC') `) is not triggered when setting `UR.autoconvert_offset_to_baseunit = True`:

```python
import pint
ureg = pint.UnitRegistry()
Q_ = ureg.Quantity
ureg.autoconvert_offset_to_baseunit = True  # <- fi you comment this you get the exception
test1 = Q_('50 degC')  
print (test1.to('kelvin')  )
```

**Comment by cpascual** [comment] 2018-06-26 08:00
Regarding the second issue (`Q_('nan meters') `), I personally did not expect that `"nan"`  should be parsed as numpy.nan ...  but in any case, the Exception type is a bit misleading

**Comment by dalito** [comment] 2018-06-26 13:57
```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32               
Type "help", "copyright", "credits" or "license" for more information.                                       
>>> import pint                                                                                              
>>> ureg = pint.UnitRegistry()                                                                               
>>> Q_ = ureg.Quantity                                                                                       
>>> test1 = Q_('50', 'degC')                                                                                 
>>> test1                                                                                                    
<Quantity(50, 'degC')>                                                                                       
>>> test1.to('K')                                                                                            
Traceback (most recent call last):                                                                           
  File "<stdin>", line 1, in <module>                                                                        
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\quantity.py", line 332, in to                       
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)                          
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\quantity.py", line 300, in _convert_magnitude_not_in
place                                                                                                        
    return self._REGISTRY.convert(self._magnitude, self._units, other)                                       
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\registry.py", line 686, in convert                  
    return self._convert(value, src, dst, inplace)                                                           
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\registry.py", line 1214, in _convert                
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)                                   
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\registry.py", line 983, in _convert                 
    value = self._units[u].converter.to_reference(value, inplace)                                            
  File "C:\dev_src\_pyve\dev_py27\lib\site-packages\pint\converters.py", line 71, in to_reference            
    value = value * self.scale + self.offset                                                                 
TypeError: cannot concatenate 'str' and 'float' objects                                                      
>>> test1.magnitude                                                                                          
'50'                                                                                                         
>>> type(test1.magnitude)                                                                                    
<type 'str'>
```                                                                                           
That the magnitude is stored as string seems like a bug to me.

**Comment by cpascual** [comment] 2018-06-26 17:58
> That the magnitude is stored as string seems like a bug to me.

@dalito . The first time I saw it, it also seemed strange to me, but now I see it as a feature of pint, not a bug: if you use the `Q_(magnitude, unit) `style of call, it is kind of reasonable that no evaluation is done on magnitude (note that this is different from initializing from a string as in `Q_(string)`). This way you can define Quantities with arbitrary objects for the magnitude (e.g. with your own implementation of base 10 decimal).

**Comment by dalito** [comment] 2018-06-26 20:01
@cpascual Thanks for the explanation. I have never tried to use pint like that.

**Comment by hgrecco** [comment] 2018-07-12 01:12
I agree with @cpascual Regarding "nan meters", maybe we can think of realistic use cases to decide what is the right behavior.

**Comment by hgrecco** [comment] 2019-12-03 22:17
Closing. Feel free to reopen or open a new updated issue.

**Closed by hgrecco** 2019-12-03 22:17 UTC
