### ISSUE TITLE
Running pint from IronPython

### ISSUE THREAD

**Issue by AndyJRSmith** [hgrecco/pint#720] opened 2018-10-15 12:39 UTC
Pint doesn't have a particularly happy time running in IronPython. 

First, the contexts in `default_en.txt` won't load - as a temporary workaround I just deleted them because I don't need them. 

Secondly, line 505 of `compat.tokenize` (inside `_tokenize` function) fails with an unhandled exception because a `ValueError` is raised instead of a `StopIteration`.

**Comment by hgrecco** [comment] 2018-10-16 00:14
I would be very happy to fix this but I cannot test this. My suggestions:
1. default_en.txt: I guess that the problem here is how Pint is looking for package data. Maybe this is not standarized across interpreters.
2. this is hard to say, 505 just calls a function that reads a line. Can you provide more info?

**Comment by AndyJRSmith** [comment] 2018-10-18 14:17
I haven't had time to investigate (1). However, (2) looks like it could be a bug in IronPython's `iter(o, sentinel)` method.

in cpython 2.7.15:
```
>>>i = iter([3,2,1].pop, 4)
>>>i.next()
3
>>>i.next()
2
>>>i.next()
Traceback ... StopIteration
```

in cpython 3.6.6:
```
>>>i = iter([3,2,1].pop, 4)
>>>i.__next__()
3
>>>i.__next__()
2
>>>i.__next__()
Traceback ... 
StopIteration
```

in IronPython:
```
>>>i = iter([3,2,1].pop, 4)
>>>i.next()
Traceback ...
ValueError
```

**Comment by hgrecco** [comment] 2019-12-21 05:00
Cannot reproduce. Closing. Feel free to reopen.

**Closed by hgrecco** 2019-12-21 05:00 UTC
