### ISSUE TITLE
Converting Measurement units

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#279] opened 2015-06-24 18:47 UTC
I know measurements (with errors) are not fully supported, but am wondering if I am doing something wrong that I can't even convert units...

```python
x = ((ureg.m/ureg.s).plus_minus(1)).to(ureg.m/ureg.day)
```

```python
Traceback (most recent call last):
  File "<ipython-input-163-b61fb6cbf2eb>", line 1, in <module>
    x = ((ureg.m/ureg.s).plus_minus(1)).to(ureg.m/ureg.day)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py", line 241, in to
    other = UnitsContainer(other)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/unit.py", line 342, in __init__
    dict.__init__(self, *args, **kwargs)
  File "/Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py", line 978, in __iter__
    it_mag = iter(self.magnitude)
TypeError: 'float' object is not iterable

> /Users/mankoff/local/anaconda/lib/python3.4/site-packages/pint/quantity.py(978)__iter__()
    977         # Allow exception to propagate in case of non-iterable magnitude
--> 978         it_mag = iter(self.magnitude)
    979         return iter((self.__class__(mag, self._units) for mag in it_mag))
```

**Comment by ryanpdwyer** [comment] 2015-06-24 19:43
This works if you use a string as the `to` argument ( `to('meter/day')`). The problem is in the definition of the `to` method. 

```
def to(self, other=None, *contexts, **ctx_kwargs):
        """Return Quantity rescaled to different units.

        :param other: destination units.
        :type other: Quantity, str or dict
        """
        if isinstance(other, string_types):
            other = self._REGISTRY.parse_units(other)
        elif isinstance(other, self.__class__):
            other = copy.copy(other.units)
        elif isinstance(other, UnitsContainer):
            pass
        else:
            other = UnitsContainer(other)

        magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)

        return self.__class__(magnitude, other)
```

Normally, we would want your example code to be caught by,

```python
        elif isinstance(other, self.__class__):
            other = copy.copy(other.units)
```

The code is checking to see if `other` is a subclass of `self` (a `Measurement`), which is not true; `Measurement` is a subclass of `Quantity`, so`UnitsContainer` is called on `other`, which raises an error.

Solutions:

1. Change the `isinstance(other, self.__class__)` check to `isinstance(other, Quantity)`.
2. I like, 

```python
elif hasattr(other, 'units') and isinstance(other.units, UnitsContainer):
    other = copy.copy(other.units)
```

**Comment by ryanpdwyer** [comment] 2015-06-24 19:55
I see it's already been fixed in the develop branch.

**Comment by hgrecco** [comment] 2015-06-24 23:50
Thanks for answering this. I think is really time to release a new version. I will wrap up my changes to the systems on the weekend and do it.

**Closed by hgrecco** 2015-06-24 23:50 UTC
