### ISSUE TITLE
Quantity operator overloading does not play well with others

### ISSUE THREAD

**Issue by bqpd** [hgrecco/pint#256] opened 2015-03-14 18:39 UTC
Unless I'm missing something, it seems that `Quantity.__add__` and so on should return `NotImplemented` instead of raising a `DimensionalityError`? This would allow pints to be used together with other libraries that use operator overloading. In [gpkit](https://github.com/convexopt/gpkit) we use a [kind of awful hack](https://github.com/convexopt/gpkit/blob/master/gpkit/__init__.py#L61) to get around this, though I'm potentially just doing it wrong.

(unrelatedly, pints is great, and thanks for your work in putting it together!)

**Comment by hgrecco** [comment] 2015-03-15 18:17
Thanks for the support. The problem is how to deal with user defined numerical classes. Imagine that you do `X+Y` where `X` is a Pint quantity and `Y` is something else. 

(A) If `Y is a number, then
- if `X` is dimensionless, you want to return `X.to('') + Y`
- if `X` is not dimensionless, you want to raise a `DimensionalityError`.

(B) If `Y` is not a number, then you would like to return `NotImplemented`

Because we do not have good way to say if something is a number or not we decided to implement only A. We are open to suggestions in this regard.

But tell us more about your use case, maybe we can find a way to support it.

**Comment by bqpd** [comment] 2015-03-15 18:25
Huh, interesting! You're saying that if `1 + units.m` is run, you want the error to read `DimensionalityError: Cannot convert from 'meter' to 'dimensionless'` instead of `TypeError: unsupported operand type(s) for +: 'int' and 'pint.unit.Quantity'`, presumably because the latter is less clear as to what the error message is?

I wonder, how do integers / floats in python determine if something is a number?

My use case in gpkit is making a symbolic math object (e.g. `x**2 + y`) that has units (but is not a Quantity), and that is overloaded to allow adding to numbers and other symbolic math objects.

**Comment by hgrecco** [comment] 2015-03-16 03:59
I think the usual way is that they return `NotImplemented` and let the other class (e.g. numpy's ndarray) handle it. The problem with that approach is that we will need to make a list of all the things that could be handled by Pint. This includes all python numerical types, all numpy numerical types (we have something like this `compat.NUMERIC_TYPES`. But he other problem still is that this wont work with user defined numerical classes.

A few questions about your case:
- Can you derive from Quantity?
- How does Pint's quantities get into the equation? Something like `q * x **2 + y` where `q` is a quantity?

**Comment by bqpd** [comment] 2015-03-16 19:50
I don't think we can derive from Quantity while still working for users who do not have pints installed.

That is one way for pint's quantities to get in; another way is in variable declaration, e.g.

```python
x = gpkit.Variable("x", "meters")
```

How about looking for a "I'm not a numerical class" flag that's specific to pint? E.g., `if hasattr(other, "__pintimnotanumber"): return NotImplemented`

**Comment by hgrecco** [comment] 2015-12-22 03:38
I am closing this now. Feel free to reopen.

**Closed by hgrecco** 2015-12-22 03:38 UTC

**Comment by alexfeld** [comment] 2016-03-03 20:05
I think this issue is the cause of #278. It appears that Quantity is forcing all other objects to go through it's math. This makes sense in most cases since you want units to propagate. However, what it does is force all of the right hand operations to return Quantities and it prevent left hand operator overloads from working properly.

As for a fix, what about making it so that the Quantity math operators check for the existence of a units property (built off of Pint) in the other object? This would allow other users to build off of Pint's units without messing up their code or forcing them to use their own hacked version of Pint's automatic unit conversion or forcing them to inherit from Quantity if they don't need to. Perhaps that would go against the philosophy of the pint package. If so, it would be nice to get clarification on this issue.

**Comment by whoburg** [comment] 2016-11-03 20:46
Putting in a vote for reopening this!
