### ISSUE TITLE
Print delta_degC

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#272] opened 2015-05-11 18:19 UTC
It would be nice to be able to print `degree` units.

```python
>>> c = ureg.Quantity(1, ureg.delta_degC)
>>> print c
Traceback (most recent call last):
  File "<ipython-input-73-8e698a6f794d>", line 1, in <module>
    print c
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0394' in position 2: ordinal not in range(128)

> <ipython-input-73-8e698a6f794d>(1)<module>()
----> 1 print c

ipdb> 
>>> 
```

I have `default_format` set to `~`. Should it be something different?

**Comment by hgrecco** [comment] 2015-05-30 15:36
```python
>>> import pint
ureg = pint.UnitRe>>> ureg = pint.UnitRegistry()
>>> c = ureg.Quantity(1, ureg.delta_degC)
>>> c
<Quantity(1, 'delta_degC')>
>>> print(c)
1 delta_degC
>>> ureg.default_format = '~'
>>> print(c)
1 Δcelsius
```

My guess is that your terminal is not properly configured to show UTF-8

**Comment by mankoff** [comment] 2015-05-30 15:52
I'm using Python 2.7. Are you using 3.x? Isn't 3 more UTF-8 compliant than 2?

**Comment by hgrecco** [comment] 2015-05-30 15:59
Python 3 is more compliant. But many times the problem is due to the terminal, not Python

**Comment by mankoff** [comment] 2015-05-30 16:04
I'm not sure how to verify if my Terminal does UTF-8 or now, but I'm on OS X and I can have all sorts of neat things show up in my prompt like the ∆ (Delta) symbol and emoji's and etc, so I don't think it is a UTF-8 issue.

**Comment by coldfix** [comment] 2015-05-30 16:22
Sorry to tag in. This doesn't look like a terminal problem to me (terminal problems won't raise python exceptions). The error message states that the text can't be encoded as ascii, not utf-8. I think, I had this problem before myself, I'll have a short look, if I can find whether I solved it.

**Comment by mankoff** [comment] 2015-05-30 16:26
Don't apologize for dropping in! I've just checked with a Python 3 virtual env and it works. This is a Python 2 issue.

**Comment by coldfix** [comment] 2015-05-30 16:43
Okay, I don't recall exactly, but I believe it has something to do with the python2 magic method `__str__` or `__format__` returning `str` (which is `bytes`, not `unicode`) by default. Python2 then implicitly tries to convert the `unicode` returned by pint to `bytes` using ASCII.

Try if the following works:

```python
print unicode(c)
```

At the time, I needed it, I created a custom function to format units which also does some more pretty printing. In case you're interested, this is the part that only formats the unit part:

```python
def get_raw_label(quantity):
    """Get the name of the unit, without enclosing brackets."""
    short = pint.unit.UnitsContainer(
        {ureg._get_symbol(key): value
         for key, value in quantity.units.items()})
    as_ratio = any(exp > 0 for _, exp in short.items())
    return pint.formatting.formatter(
        short.items(),
        as_ratio=as_ratio,
        single_denominator=True,
        product_fmt=u'·',
        division_fmt=u'/',
        power_fmt=u'{0}{1}',
        parentheses_fmt=u'({0})',
        exp_call=pint.formatting._pretty_fmt_exponent,
    )
```

**Comment by ryanpdwyer** [comment] 2015-05-30 16:45
Yeah, with that default formatter, the Quantity object is returning unicode from `__str__` (which print calls behind the scenes), which is bytes only in python2.

As a temporary fix, calling `format(c)`, or `print format(c)` will work, or defining a function like,

```python
def print_(x):
    print u'{}'.format(x)
```
On the pint end of it, to avoid this error, `Quantity.__str__` would have to return `str(format(self).encode('utf8'))`, rather than `format(self)` in python2.

**Comment by hgrecco** [comment] 2015-05-30 17:00
It is not a python2 issue. The output that I showed works the same way in Python 2 and 3.

Try running this commands in your terminal first:
```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export PYTHONIOENCODING=utf-8
```

**Comment by mankoff** [comment] 2015-05-30 17:19
Same issue even with those environment variables. With or without them (in Python3) there is no problem.

**Comment by hgrecco** [comment] 2015-05-30 17:40
I have double checked @coldfix  You are right, There is a problem with Python 2. I am sorry for the noise.

**Comment by coldfix** [comment] 2015-05-30 19:58
No problem. There is a way to tell your python to use encodings other than ascii for the implicit conversions that take place in 2.X:

```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

with this enabled, `__str__` can successfully encode its return value to `str`. I've never actually seen anyone do this, but maybe this was the reason that the code didn't except on your machine.

The snippets by @ryanpdwyer are IMO the way to go here: In python2 the `__str__` method should encode its return value using some specified encoding - probably using from `locale.getpreferredencoding()`. If you don't feel this should be changed in pint, the `u"".format(quantity)` is the best python2/3 portable way to receive unicode strings.

**Comment by hgrecco** [comment] 2015-05-30 21:22
I am not against changing this in Pint as long as we do not disrupt existing users.

**Comment by MatthieuDartiailh** [comment] 2015-05-30 23:00
You vould also use future  http://python-future.org/compatible_idioms.html#custom-str-methods to avoid that kind of issues I believe.

**Comment by herman5** [comment] 2015-12-08 14:33
@hgrecco is the fix from @coldfix going to be merged? I have encountered this issue as well and would like to see the solution in the next release

**Comment by hgrecco** [comment] 2015-12-22 03:31
Sorry for the long delay. Merged now.

**Closed by hgrecco** 2015-12-22 03:31 UTC
