### ISSUE TITLE
Problem with Setuptools

### ISSUE THREAD

**Issue by metroid120** [hgrecco/pint#1008] opened 2020-02-01 12:16 UTC
Hello guys, I have found a problem with setuptools.

In File quantity.py I needed to replace:
`from pkg_resources.extern.packaging import version`

with
`# from packaging import version`

I think pkg_resources.extern is no longer provided by setuptools.
This is the first time I am writing something on Github, maybe you can point me to
a resource or tell me what to do in case I find such bugs in open sources projects.

**Comment by hgrecco** [comment] 2020-02-02 22:49
Cannot reproduce. Please provide the versions of the different packages you are using.

**Comment by metroid120** [comment] 2020-02-03 11:16
I am using:
-setuptools 44.0.0
-pint 0.10.2dev branch
-python 3.8.1

**Comment by hgrecco** [comment] 2020-02-06 22:13
I think your installation of setuptools is incomplete as `packaging` is included within the `extern` part of `setuptools`.  Are you running this on linux, by chance?

**Comment by metroid120** [comment] 2020-02-07 08:21
Yes I am using linux (arch).

**Comment by hgrecco** [comment] 2020-02-10 02:04
I am pretty sure that you setuptools instalation is broken. `packaging` is an extern part of setuptools. Maybe [this](https://github.com/pypa/setuptools/issues/514) happened or similar. I would suggest you do a clean install. I am closing now, feel free to reopen if needed.

**Closed by hgrecco** 2020-02-10 02:04 UTC

**Comment by dev-zero** [comment] 2020-04-07 14:50
Since I hit the very same issue after doing a `pip install --user myproject` which depends on `pint` I followed the leads a bit. The cause is that some Linux distributions like Arch Linux have stopped including the vendored `packaging` package (which was part of `setuptools`):

* https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python-setuptools
* https://github.com/pypa/setuptools/issues/1383

So yes, you should directly be using `packaging` rather than relying on `setuptools`' import of the `packaging` library to make it work in any case.

**Comment by keewis** [comment] 2020-04-07 15:14
thanks for investigating. My reason for choosing to use `pkg_resources.extern.packaging` instead of directly using `packaging` was to avoid adding another (direct) dependency to `pint`. If that decision causes problems, I guess we should change that (unless there are any objections?).

Do you want to submit a PR?

**Comment by jules-ch** [comment] 2020-04-07 15:23
Btw pkg_resources from setuptools can be replaced with standard library importlib.metadata & importlib.resources from Python 3.8.
There are backports for both.

**Comment by keewis** [comment] 2020-04-07 15:33
thanks for the tip. Unless I'm missing something, neither of those libraries provide version comparison, though? (`distutils` does, but neither `LooseVersion` nor `StrictVersion` correctly compare the versions `setuptools_scm` creates)

**Comment by dev-zero** [comment] 2020-04-07 15:50
and Duck typing wouldn't work?

```python
    def __matmul__(self, other):
        try:
            # Use NumPy ufunc (existing since 1.16) for matrix multiplication
            return np.matmul(self, other)
        except AttributeError:
            return NotImplemented
```

**Comment by keewis** [comment] 2020-04-07 16:03
`numpy.matmul` was introduced in `1.10`, but it wasn't a `ufunc` until `1.16` (making it overridable using `__array_ufunc__`). Since the minimum `numpy` version `pint` supports is `1.14`, I think we still need the version check (but I might be mistaken).

@jthielen, any thoughts on this?

**Comment by jthielen** [comment] 2020-04-07 16:44
@keewis Indeed, `np.matmul`'s behavior is only correct with Pint Quantities since version 1.16 when it became a ufunc, so checking for an AttributeError in Quantity's `__matmul__` would be insufficient. To remove the version check (or to work with NumPy pre-1.16), there would need to be custom unit checking/handling code in `__matmul__`. When implementing `__matmul__` here, I had assumed most people would be on recent NumPy versions, so that it wasn't worth the effort, and the version check was good enough.

However, if the version check needs to be removed, I'm sure a PR would be welcome to do so.

**Comment by keewis** [comment] 2020-04-07 16:50
I think it should be enough to add the (currently indirect) dependency `packaging` as a direct dependency (and also change the import) and remove the version check once we require `numpy >= 1.16`.

With that said, @dev-zero: do you want to put in a PR? Otherwise I'd do it.
