### ISSUE TITLE
Dimensionless Quantities behave unexpectedly with scipy.special.erf and casting to numpy floats

### ISSUE THREAD

**Issue by natezb** [hgrecco/pint#250] opened 2015-03-08 19:17 UTC
Related to #45 and #170.

I noticed this while using `scipy.special.erf`, I'm not sure what other functions it applies to, and I'm not familiar with the internals of scipy so I don't know why `Quantity.__float__` seems to be circumvented.

I also noticed that casts to `np.float16`, `np.float32`, and `np.float128` all produced an incorrect result.

    >>> np.float32(u.V/u.mV)
    1.0  # Should be 1000.0

Casting to `np.float64` works as expected.

**Comment by hgrecco** [comment] 2015-03-09 20:13
I will look into `erf`, but float works fine for me in the current develop:
```python
>>> np.float32(ureg.V/ureg.mV)
1000.0
>>> np.float16(ureg.V/ureg.mV)
1000.0
>>> np.float128(ureg.V/ureg.mV)
1000.0
>>> np.float64(ureg.V/ureg.mV)
1000.0
```

**Comment by natezb** [comment] 2015-03-09 21:46
I am testing using Pint 0.6, Python 3.4.2 64-bit, and Numpy 1.9.1. I also get the issue with Python 2.7.9 and the same versions of Pint and Numpy.

I just downloaded and used develop and the problem still exists for both Python 2 and 3.

I'm running Archlinux on a 64-bit machine.

**Comment by hgrecco** [comment] 2015-03-10 10:36
I have added a test for np.floatXX and they all pass in travis. This is a 64 bit linux, 64-bit Python 2.6 - 3.4 and Numpy from 1.6 to 1.9.

**Comment by natezb** [comment] 2015-03-10 20:08
Ok, so I've been poking around a bit using the `pdb` module.

When I use np.floatXX (where XX != 64), Numpy tries to access `Quantity.__array_struct__`. This calls `Quantity.__getattr__`, which calls `compat._to_magnitude`, which ultimately calls `np.asarray` on the quantity's magnitude. So this magnitude, cast to an ndarray (but otherwise not checked for nondimensionality) is what gets returned to whatever numpy code is asking for `__array_struct__`.

Note that this also makes `np.float32(u.V)` valid, while `float(u.V)` raises `DimensionalityError`.

Interestingly, `np.float64` calls `Quantity.__float__` first, so if the quantity is dimensionless, it is converted appropriately and returned. However, if `__float__` raises an exception, `np.float64` catches it, ignores it, and tries `Quantity.__array_struct__` instead. Thus, calling `np.float64(u.V)` does not raise an exception, but instead returns `1.0`.

I don't know why this is happening on my system and not yours. The solution on my end would be to check for (non)dimensionality when looking for `__array_x` attributes, but I'm not sure if that would cause existing code to fail.

**Comment by hgrecco** [comment] 2015-03-11 00:14
Strange. Do you have `force_ndarray` or any other option set to a non-default value?

**Comment by natezb** [comment] 2015-03-11 16:11
Where are these options set? It's possible I've changed some, but I don't recall where the file is.

**Comment by hgrecco** [comment] 2015-03-11 20:06
On construction of the `UnitRegistry`, there is not other place. So I guess you have not changed that. I will look into this and come back to you.

**Comment by hgrecco** [comment] 2015-12-22 03:40
I am closing this now as I cannot reproduce. Feel free to reopen.

**Closed by hgrecco** 2015-12-22 03:40 UTC
