### ISSUE TITLE
Final sprint for 0.21, proposal for 0.22 and 0.23

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1751] opened 2023-04-26 21:20 UTC
I have merged some important PRs, but I would like your feedback to know if there is any particular and uncontroversial one that needs to be merged as well.

My goal is to release 0.21 on May 1st.

Then I will start a short refactoring sprint (no new features or bug fixes) to make a release on May 8th. This will be focused on:
1. Moving some (internal) code to delegates (for composition over inheritance).
2. Modernizing code.
3. Modernizing and improving the annotations.
4. Finish improving the infrastructure (I have moved pint to ruff, but there is still work to be done)

Importantly, 0.22 will require Python 3.9+ and NumPy 1.21+ as per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). Yes, we could drop it for 0.21, but I think it would be nice to have a last Python 3.8 version. 

Why such a short time between releases? To force that next PRs are based on the new code to avoid complex merges.
Why not just refactor now and release it in 0.21? Because I would like to have a version that works as a landmark before refactoring. And serves those still using Python 3.8.

Then we start considering PRs for 0.23.

What do you think? @jules-ch

**Comment by dopplershift** [comment] 2023-04-26 22:56
I think #1608, despite the discussion that took place there, is pretty simple.

I wouldn't mind thoughts on #1594 (I wouldn't mind having that before a refactor takes place)

**Comment by hgrecco** [comment] 2023-04-26 23:14
@dopplershift Agreed with #1594 There is a small bug that I have commented on. Do you want to implement the same for cross and dot?

**Comment by hgrecco** [comment] 2023-04-26 23:25
@dopplershift I also agree with #1608

**Comment by MichaelTiemannOSC** [comment] 2023-04-27 09:57
I would really like to know what's needed to get https://github.com/hgrecco/pint/pull/1615 considered in one of these releases.  I really don't want to try to support the OS-Climate project from a fork of pint.

**Comment by jules-ch** [comment] 2023-04-28 20:51
Thanks for the work on issues and PR @hgrecco.
I had a lot on my plate lately.
I haven't had time to contribute or review PR last months.

I'm ok with the plan you described.

**Comment by jules-ch** [comment] 2023-04-28 20:57
One side effect of the new structure of facets had been the complex inheritance types that broke most of the work I have done to have a better type annotation experience 1679 + some public facing APIs (functions and class) have been moved that broke some code. 

Well we are still in 0.x version, but we can ease the transition


Some thoughts on the roadmap, I also want to transition from text registry to a standard file format instead of parsing it.
To get registry from it: file -> dict/dataclasses -> Registry.

**Comment by jules-ch** [comment] 2023-04-28 20:58
+1 on the last python 3.8 version

**Comment by hgrecco** [comment] 2023-04-29 13:42
> One side effect of the new structure of facets had been the complex inheritance types that broke most of the work I have done to have a better type annotation experience 1679 + some public facing APIs (functions and class) have been moved that broke some code.

Indeed. I think that I have a solution for this. Briefly, instead of dynamically creating the Quantity/Unit classes I will do it statically. And to ensure compliance with the registry, I will check the inheritance.

> Some thoughts on the roadmap, I also want to transition from text registry to a standard file format instead of parsing it. To get registry from it: file -> dict/dataclasses -> Registry.

I am still having a hard time to find a nice format. But, as I said before, I am open. And the delegates and facets rework was a milestone to produce a clear separation between definition in file, definition in memory as objects and operative objects within the registry. It should be very easy now to produce a new parser that emits facets definitions and that we can test side by side.

**Comment by MichaelTiemannOSC** [comment] 2023-04-29 13:46
Former compiler guy here.  Text-based formats are the worst, except for all the rest.  What's wrong with having a text-based format that works so well for source-level management, and then instantiating and pickling the results appropriately on install?

**Comment by hgrecco** [comment] 2023-04-29 13:47
I am feature freezing 0.21. There is one group of tests that is failing.

3.8, numpy, uncertainties, sparse xarray netCDF4 dask[complete] graphviz babel==2.8

https://github.com/hgrecco/pint/actions/runs/4839002449/jobs/8623770330

That I fail to understand the reason.

**Comment by hgrecco** [comment] 2023-04-29 13:48
> I would really like to know what's needed to get #1615 considered in one of these releases. I really don't want to try to support the OS-Climate project from a fork of pint.

I have labeled this for 0.23 . The tokenizer/evaluator is at the heart of pint, I would rather not do it in the last Python 3.8 compatible version.

**Comment by hgrecco** [comment] 2023-04-29 14:00
> Former compiler guy here. Text-based formats are the worst, except for all the rest. What's wrong with having a text-based format that works so well for source-level management, and then instantiating and pickling the results appropriately on install?

My understanding is that @jules-ch is proposing to change the current text format by another text format but based on a standard (json, yaml, toml, or something). Definitions will be read from those files as dicts, and the imported into the (facets) definition objects. 

What I like about the proposed approach: you get a reader/writer (almost) for free.
What I like about the current approach: the current Pint format is proven, uncluttered and nice to read (in am biased here).
What is out of the table: writing definitions within a python file or in a binary file. Definitions in Pint should always be parsed.

Thanks to the cache addition, we can have a pickled fast intermediate version.

**Comment by jules-ch** [comment] 2023-04-29 14:05
Culprit seems to be this commit 5cedf99

**Comment by hgrecco** [comment] 2023-04-29 14:09
@jules-ch I thought the same as first but it does not make sense to me. I wonder if this is something external to Pint (I tried downgrading dask with no success)

**Comment by jules-ch** [comment] 2023-04-29 14:17
I cannot reproduce on local it probably comes from one of the dependencies.

**Comment by jules-ch** [comment] 2023-04-29 14:26
It comes from this commit commit 77ff32a8e31164a9eedc4170924579b2911ed19e

**Comment by jules-ch** [comment] 2023-04-29 15:06
Found what was wrong, missing:

- missing imports and code was not working properly for the new is_upcast method.
I'm making a PR

**Comment by jules-ch** [comment] 2023-04-29 15:31
Fixed in #1762

**Comment by hgrecco** [comment] 2023-05-01 13:29
Just released 0.21. Let's check that everything is fine and we announce it.

**Comment by hgrecco** [comment] 2023-05-01 13:40
GitHub default branch is now called `main` (not master) in most applications, sites, etc. Shall we make this change to simplify tooling?

**Comment by keewis** [comment] 2023-05-01 14:00
I don't think we need to do that due to the tooling, but let's do it anyways

**Comment by hgrecco** [comment] 2023-05-01 22:35
I just merge a large code change in a path to 0.22. It is still a work in progress, but I very much like your input.

There is a particular aspect that I am not sure about: the definition of a numeric (scalar and array) [protocol](
https://github.com/hgrecco/pint/blob/556aeea0d363f5757c42296ad66ffe47f05c02b2/pint/_typing.py#L14) to be used in different part of Pint code. This seems to work much better for typing than using `numbers.Number` or the union of all [numeric types](https://github.com/hgrecco/pint/blob/556aeea0d363f5757c42296ad66ffe47f05c02b2/pint/compat.py#L67)

**Comment by hgrecco** [comment] 2023-05-01 22:45
Please remember that the code base is frozen until May 8th for anything except the objectives defined for 0.22. No new features, no bug fixes (except those appearing from improving typing support).

**Comment by jules-ch** [comment] 2023-05-03 09:59
Shall we make a dedicated issue about types @hgrecco.
If you have any ideas or thoughts on the matter, I'm open ot discussion.

**Comment by hgrecco** [comment] 2023-05-05 06:36
Just pushed a large typing related commit. Still WIP but looking better. I will open another Issue

**Comment by hgrecco** [comment] 2023-05-05 17:50
Was anybody able to test the current master?

**Comment by jules-ch** [comment] 2023-05-05 17:56
Careful about tuple typing, you need to add elispis `...` to tell it's a tuple with an unlimited amount.

Like `tuple[str, ...]` to say a tuple with unlimited amount of `str`. I saw you removed them for some types.

https://docs.python.org/3/library/typing.html#typing.Tuple

**Comment by hgrecco** [comment] 2023-05-09 23:26
Pint 0.22 is almost ready, just two test failing in `test-linux (3.9, numpy, uncertainties, sparse xarray netCDF4 dask[complete]==2023.4.0 graphviz babel`

**Comment by hgrecco** [comment] 2023-05-13 23:04
I had to mark two tests as xfail See #1776 but except for that it is looking good. I propose we release a rc on monday, and 0.22 the next monday.

**Closed** 2023-06-14 19:16 UTC
Labels: Roadmap
