### ISSUE TITLE
Importing pint is potentially slow due to `importlib.metadata.version`

### ISSUE THREAD

**Issue by jmrgibson** [hgrecco/pint#1279] opened 2021-03-31 03:12 UTC
Hi, I use pint as part of a pytest suite, and I'm trying to reduce the initialization time before we actually start executing tests. 
At the moment, I'm spending 0.3 seconds importing `pint`, due to `importlib.metadata.version()` on [this line](https://github.com/hgrecco/pint/blob/master/pint/__init__.py#L38). 

The majority of the time seems to be spent on [these two lines](https://github.com/python/cpython/blob/v3.8.8/Lib/importlib/metadata.py#L407-L408) in the stdlib.

This may be an issue `importlib.metadata` itself, and so feel free to tell me to go away because this is someone else's problem :)

I'm not that familiar with how dist-info works, but is there something about my or pints configuration that is causing this to take so long? 0.3 seconds for import is significantly longer than any other packages (only scipy and numpy are ~0.1 seconds each, all the others are much smaller)

Setup: 
- python3.8.8 
- Mac OSX 
- pint version 0.16.1
- pint is installed in a [shiv](https://github.com/linkedin/shiv), which is a self-extracting executable zipfile. The shiv is "warm" so the zipfile is already extracted by the time I start profiling
- using py-spy 0.35 as the profiler

Thanks

**Comment by jules-ch** [comment] 2021-04-03 09:57
You can profile import time with the followng command:

`python -X importtime -c "import pint"`

Looking at the result a good amount is caused by numpy import.
But nothing coming from `importlib.metadata`


On my machine :

<details><summary>pint (Python3.8, numpy) 282 ms</summary>
<p>

```
import time: self [us] | cumulative | imported package
import time:       510 |        510 | _frozen_importlib_external
import time:       664 |        664 |   time
import time:       393 |       1057 | zipimport
import time:        70 |         70 |     _codecs        
import time:       936 |       1005 |   codecs
import time:      1122 |       1122 |   encodings.aliases
import time:      2033 |       4159 | encodings
import time:       858 |        858 | encodings.utf_8    
import time:       962 |        962 | encodings.cp1252   
import time:        89 |         89 | _signal
import time:       586 |        586 | encodings.latin_1  
import time:       122 |        122 |     _abc
import time:       850 |        971 |   abc
import time:       739 |       1710 | io
import time:       133 |        133 |       _stat        
import time:       639 |        771 |     stat
import time:      1273 |       1273 |     _collections_abc
import time:       546 |        546 |       genericpath   
import time:      1392 |       1937 |     ntpath
import time:      1349 |       5329 |   os
import time:       612 |        612 |   _sitebuiltins     
import time:        90 |         90 |     _locale
import time:       654 |        744 |   _bootlocale       
import time:      1216 |       1216 |   sitecustomize     
import time:      3661 |      11560 | site
import time:      1125 |       1125 |         types
import time:      1707 |       2832 |       enum
import time:        73 |         73 |         _sre
import time:       882 |        882 |           sre_constants
import time:      1030 |       1911 |         sre_parse
import time:      1220 |       3204 |       sre_compile
import time:        80 |         80 |             _operator
import time:      1091 |       1170 |           operator
import time:      1059 |       1059 |           keyword
import time:        73 |         73 |             _heapq
import time:      1140 |       1213 |           heapq
import time:       241 |        241 |           itertools
import time:       958 |        958 |           reprlib
import time:       127 |        127 |           _collections
import time:      2683 |       7449 |         collections
import time:        73 |         73 |         _functools
import time:      1387 |       8907 |       functools
import time:      1127 |       1127 |       copyreg
import time:      1885 |      17952 |     re
import time:       660 |        660 |       _weakrefset
import time:      1260 |       1920 |     weakref
import time:        75 |         75 |           math
import time:       627 |        627 |             token
import time:      1728 |       2355 |           tokenize
import time:       913 |        913 |               numbers
import time:       921 |        921 |               collections.abc
import time:      2024 |       3858 |             _decimal
import time:       927 |       4784 |           decimal
import time:       687 |        687 |             warnings
import time:       783 |        783 |             numpy._globals
import time:       652 |        652 |             numpy.__config__
import time:       504 |        504 |             numpy.version
import time:       599 |        599 |                   posixpath
import time:       722 |       1320 |                 fnmatch
import time:       908 |       2227 |               glob
import time:      3896 |       3896 |                 _ctypes
import time:       120 |        120 |                   _struct
import time:       875 |        994 |                 struct
import time:       904 |        904 |                 ctypes._endian
import time:      2013 |       7807 |               ctypes
import time:      1778 |      11812 |             numpy._distributor_init
import time:      1536 |       1536 |                   textwrap
import time:       137 |        137 |                       _datetime
import time:      1636 |       1772 |                     datetime
import time:      2269 |       4041 |                   numpy.core._multiarray_umath
import time:       747 |        747 |                       numpy.compat._inspect
import time:        88 |         88 |                           errno
import time:       711 |        711 |                             urllib
import time:      1786 |       2496 |                           urllib.parse
import time:      1647 |       4231 |                         pathlib
import time:       398 |        398 |                         pickle5
import time:      1154 |       1154 |                           _compat_pickle
import time:       126 |        126 |                           _pickle
import time:       509 |        509 |                               org
import time:       223 |        732 |                             org.python
import time:       195 |        926 |                           org.python.core
import time:      1921 |       4127 |                         pickle
import time:      1172 |       9926 |                       numpy.compat.py3k
import time:      1120 |      11793 |                     numpy.compat
import time:       155 |      11948 |                   numpy.compat._inspect
import time:      1288 |      18811 |                 numpy.core.overrides
import time:      3181 |      21992 |               numpy.core.multiarray
import time:       976 |        976 |               numpy.core.umath
import time:       548 |        548 |                 numpy.core._string_helpers
import time:       522 |        522 |                   numpy.core._dtype
import time:       966 |       1488 |                 numpy.core._type_aliases
import time:      1158 |       3193 |               numpy.core.numerictypes
import time:       870 |        870 |                   numpy.core._asarray
import time:       783 |        783 |                       numpy.core._exceptions
import time:       818 |       1601 |                     numpy.core._methods
import time:      3395 |       4995 |                   numpy.core.fromnumeric
import time:      1421 |       7285 |                 numpy.core.shape_base
import time:      1016 |       1016 |                   contextlib
import time:       976 |       1991 |                 numpy.core._ufunc_config
import time:      1227 |       1227 |                 numpy.core.arrayprint
import time:      3006 |      13508 |               numpy.core.numeric
import time:      3401 |       3401 |               numpy.core.defchararray
import time:       917 |        917 |               numpy.core.records
import time:       708 |        708 |               numpy.core.memmap
import time:       896 |        896 |               numpy.core.function_base
import time:       606 |        606 |               numpy.core.machar
import time:       695 |        695 |               numpy.core.getlimits
import time:      1056 |       1056 |               numpy.core.einsumfunc
import time:       734 |        734 |                 numpy.core._multiarray_tests
import time:      1866 |       2600 |               numpy.core._add_newdocs
import time:       892 |        892 |               numpy.core._add_newdocs_scalars
import time:       656 |        656 |               numpy.core._dtype_ctypes
import time:        87 |         87 |                   _ast
import time:       925 |       1012 |                 ast
import time:      2606 |       2606 |                 platform
import time:      1545 |       5162 |               numpy.core._internal
import time:       685 |        685 |               numpy._pytesttester
import time:      4306 |      62242 |             numpy.core
import time:       917 |        917 |               numpy.lib.mixins
import time:       704 |        704 |                   numpy.lib.ufunclike
import time:      1440 |       2144 |                 numpy.lib.type_check
import time:      1437 |       3581 |               numpy.lib.scimath
import time:      1452 |       1452 |                         numpy.lib.twodim_base
import time:       778 |        778 |                         numpy.linalg.lapack_lite
import time:       726 |        726 |                         numpy.linalg._umath_linalg
import time:      2712 |       5667 |                       numpy.linalg.linalg
import time:       905 |       6571 |                     numpy.linalg
import time:       997 |       7568 |                   numpy.matrixlib.defmatrix
import time:       783 |       8350 |                 numpy.matrixlib
import time:      1322 |       1322 |                   numpy.lib.histograms
import time:      2852 |       4174 |                 numpy.lib.function_base
import time:       892 |        892 |                 numpy.lib.stride_tricks
import time:      1540 |      14955 |               numpy.lib.index_tricks
import time:      1817 |       1817 |               numpy.lib.nanfunctions
import time:      1737 |       1737 |               numpy.lib.shape_base
import time:      1541 |       1541 |               numpy.lib.polynomial
import time:      1185 |       1185 |               numpy.lib.utils
import time:      1282 |       1282 |               numpy.lib.arraysetops
import time:       612 |        612 |                 numpy.lib.format
import time:        79 |         79 |                     zlib
import time:       623 |        623 |                       _compression
import time:       956 |        956 |                       threading
import time:       748 |        748 |                       _bz2
import time:      1366 |       3691 |                     bz2
import time:       779 |        779 |                       _lzma
import time:      1124 |       1903 |                     lzma
import time:       429 |        429 |                     pwd
import time:       374 |        374 |                     grp
import time:      1841 |       8315 |                   shutil
import time:       801 |       9115 |                 numpy.lib._datasource
import time:       983 |        983 |                 numpy.lib._iotools
import time:      1956 |      12665 |               numpy.lib.npyio
import time:       724 |        724 |               numpy.lib.arrayterator
import time:       763 |        763 |               numpy.lib.arraypad
import time:       601 |        601 |               numpy.lib._version
import time:      3129 |      44890 |             numpy.lib
import time:       651 |        651 |                 numpy.fft._pocketfft_internal
import time:      1844 |       2494 |               numpy.fft._pocketfft
import time:      1188 |       1188 |               numpy.fft.helper
import time:      1069 |       4750 |             numpy.fft
import time:       744 |        744 |                 numpy.polynomial.polyutils
import time:       817 |        817 |                 numpy.polynomial._polybase
import time:      1400 |       2960 |               numpy.polynomial.polynomial
import time:      1437 |       1437 |               numpy.polynomial.chebyshev
import time:       996 |        996 |               numpy.polynomial.legendre
import time:       791 |        791 |               numpy.polynomial.hermite
import time:       735 |        735 |               numpy.polynomial.hermite_e
import time:       708 |        708 |               numpy.polynomial.laguerre
import time:      1860 |       9484 |             numpy.polynomial
import time:       402 |        402 |                       backports_abc
import time:      1400 |       1801 |                     numpy.random._common
import time:        87 |         87 |                         binascii
import time:       849 |        935 |                       base64
import time:      1199 |       1199 |                         _hashlib
import time:        77 |         77 |                           _blake2
import time:        86 |         86 |                           _sha3
import time:      1184 |       1345 |                         hashlib
import time:      1063 |       3607 |                       hmac
import time:       118 |        118 |                           _bisect
import time:       742 |        860 |                         bisect
import time:        56 |         56 |                         _sha512
import time:        72 |         72 |                         _random
import time:      1435 |       2421 |                       random
import time:      1213 |       8174 |                     secrets
import time:      1420 |      11394 |                   numpy.random.bit_generator
import time:       735 |        735 |                   numpy.random._bounded_integers
import time:       661 |        661 |                   numpy.random._mt19937
import time:      1925 |      14713 |                 numpy.random.mtrand
import time:       833 |        833 |                 numpy.random._philox
import time:       690 |        690 |                 numpy.random._pcg64
import time:       733 |        733 |                 numpy.random._sfc64
import time:      1109 |       1109 |                 numpy.random._generator
import time:      1604 |      19680 |               numpy.random._pickle
import time:       882 |      20562 |             numpy.random
import time:       944 |        944 |             numpy.ctypeslib
import time:       679 |        679 |                       _opcode
import time:       901 |       1580 |                     opcode
import time:      1048 |       2627 |                   dis
import time:       804 |        804 |                     importlib
import time:       821 |       1625 |                   importlib.machinery
import time:       781 |        781 |                   linecache
import time:      2343 |       7376 |                 inspect
import time:      3272 |      10647 |               numpy.ma.core
import time:      1664 |       1664 |               numpy.ma.extras
import time:      1230 |      13540 |             numpy.ma
import time:      4192 |     175037 |           numpy
import time:       464 |        464 |           uncertainties
import time:       349 |        349 |           babel
import time:       392 |        392 |           pint_pandas
import time:       350 |        350 |           pandas
import time:       340 |        340 |           xarray
import time:       340 |        340 |           dask
import time:      2035 |     186518 |         pint.compat
import time:       749 |     187267 |       pint.converters
import time:       734 |        734 |       pint.errors
import time:       929 |        929 |           traceback
import time:        56 |         56 |             _string
import time:      1452 |       1508 |           string
import time:        57 |         57 |           atexit
import time:      3159 |       5651 |         logging
import time:      1530 |       1530 |         fractions
import time:       551 |        551 |           pint.babel_names
import time:       932 |       1483 |         pint.formatting
import time:       555 |        555 |         pint.pint_eval
import time:      2855 |      12072 |       pint.util
import time:      1157 |     201228 |     pint.definitions
import time:      1750 |     222849 |   pint.context
import time:       380 |        380 |             org
import time:       174 |        553 |           org.python
import time:       142 |        695 |         org.python.core
import time:       813 |       1508 |       copy
import time:      1434 |       1434 |       locale
import time:      2011 |       2011 |       typing
import time:       672 |        672 |         __future__
import time:       749 |        749 |         packaging.__about__
import time:      1347 |       2767 |       packaging
import time:       496 |        496 |         packaging._structures
import time:       479 |        479 |         packaging._typing
import time:      2777 |       3751 |       packaging.version
import time:      1044 |       1044 |       pint.numpy_func
import time:      1927 |      14439 |     pint.quantity
import time:       797 |      15236 |   pint.measurement
import time:       696 |        696 |     pint.registry_helpers
import time:      1099 |       1099 |     pint.systems
import time:       896 |        896 |       tempfile
import time:      1140 |       1140 |       importlib.abc
import time:      1147 |       3182 |     importlib.resources
import time:      1820 |       6796 |   pint.registry
import time:       736 |        736 |   pint.unit
import time:        94 |         94 |       _csv
import time:       959 |       1053 |     csv
import time:       716 |        716 |     email
import time:       580 |        580 |       importlib.util
import time:      1310 |       1890 |     zipfile
import time:      2623 |       2623 |     configparser
import time:      2543 |       8823 |   importlib.metadata
import time:       775 |        775 |       email.errors
import time:       600 |        600 |           email.quoprimime
import time:       542 |        542 |           email.base64mime
import time:       619 |        619 |               quopri
import time:       639 |       1258 |             email.encoders
import time:       772 |       2029 |           email.charset
import time:      1605 |       4775 |         email.header
import time:      2113 |       2113 |             _socket
import time:       789 |        789 |               select
import time:      1330 |       2118 |             selectors
import time:      2575 |       6805 |           socket
import time:       956 |        956 |             calendar
import time:       910 |       1865 |           email._parseaddr
import time:      1684 |      10354 |         email.utils
import time:      1322 |      16451 |       email._policybase
import time:      1472 |      18697 |     email.feedparser
import time:      1065 |      19762 |   email.parser
import time:       676 |        676 |     uu
import time:       943 |        943 |     email._encoded_words
import time:       631 |        631 |     email.iterators
import time:      1580 |       3828 |   email.message
import time:      4631 |     282658 | pint
```

</p>
</details>

<details><summary>pint (Python3.8) 144 ms</summary>
<p>

```
import time: self [us] | cumulative | imported package
import time:       523 |        523 | _frozen_importlib_external
import time:       680 |        680 |   time
import time:       511 |       1191 | zipimport
import time:        79 |         79 |     _codecs
import time:      1202 |       1280 |   codecs
import time:      1301 |       1301 |   encodings.aliases
import time:      2286 |       4866 | encodings
import time:       908 |        908 | encodings.utf_8
import time:      1034 |       1034 | encodings.cp1252
import time:       131 |        131 | _signal
import time:       700 |        700 | encodings.latin_1
import time:        55 |         55 |     _abc
import time:       976 |       1031 |   abc
import time:      1226 |       2256 | io
import time:       169 |        169 |       _stat
import time:      1027 |       1196 |     stat
import time:      1465 |       1465 |     _collections_abc
import time:       719 |        719 |       genericpath
import time:      1543 |       2261 |     ntpath
import time:      1815 |       6736 |   os
import time:      1003 |       1003 |   _sitebuiltins
import time:       104 |        104 |     _locale
import time:       899 |       1002 |   _bootlocale
import time:      1207 |       1207 |   sitecustomize
import time:      4239 |      14185 | site
import time:       785 |        785 |         types
import time:      1430 |       2215 |       enum
import time:       102 |        102 |         _sre
import time:       840 |        840 |           sre_constants
import time:      1231 |       2071 |         sre_parse
import time:      1341 |       3513 |       sre_compile
import time:        81 |         81 |             _operator
import time:      1015 |       1096 |           operator
import time:       825 |        825 |           keyword
import time:        75 |         75 |             _heapq
import time:      1250 |       1325 |           heapq
import time:       183 |        183 |           itertools
import time:       804 |        804 |           reprlib
import time:        91 |         91 |           _collections
import time:      2585 |       6906 |         collections
import time:        80 |         80 |         _functools
import time:      1489 |       8473 |       functools
import time:       951 |        951 |       copyreg
import time:      1778 |      16928 |     re
import time:       671 |        671 |       _weakrefset
import time:      1325 |       1995 |     weakref
import time:        76 |         76 |           math
import time:       723 |        723 |             token
import time:      1805 |       2527 |           tokenize
import time:      1038 |       1038 |               numbers
import time:       806 |        806 |               collections.abc
import time:      2031 |       3875 |             _decimal
import time:      1026 |       4901 |           decimal
import time:       709 |        709 |           numpy
import time:       386 |        386 |           numpy.datetime64
import time:       461 |        461 |           uncertainties
import time:       364 |        364 |           babel
import time:       368 |        368 |           pint_pandas
import time:       353 |        353 |           pandas
import time:       353 |        353 |           xarray
import time:       404 |        404 |           dask
import time:      2469 |      13366 |         pint.compat
import time:       695 |      14060 |       pint.converters
import time:       751 |        751 |       pint.errors
import time:       658 |        658 |             linecache
import time:       910 |       1567 |           traceback
import time:       972 |        972 |           warnings
import time:        61 |         61 |             _string
import time:      1560 |       1620 |           string
import time:      1087 |       1087 |           threading
import time:        64 |         64 |           atexit
import time:      3447 |       8755 |         logging
import time:      1441 |       1441 |         fractions
import time:       584 |        584 |           pint.babel_names
import time:       943 |       1527 |         pint.formatting
import time:       600 |        600 |         pint.pint_eval
import time:      2772 |      15093 |       pint.util
import time:      1180 |      31083 |     pint.definitions
import time:      1863 |      51869 |   pint.context
import time:        52 |         52 |         _bisect
import time:      1048 |       1100 |       bisect
import time:      1036 |       1036 |       contextlib
import time:       466 |        466 |             org
import time:       213 |        679 |           org.python
import time:       172 |        851 |         org.python.core
import time:       926 |       1777 |       copy
import time:       163 |        163 |         _datetime
import time:      1495 |       1657 |       datetime
import time:      1420 |       1420 |       locale
import time:      1931 |       1931 |       typing
import time:       672 |        672 |         __future__
import time:      1046 |       1046 |         packaging.__about__
import time:      1447 |       3165 |       packaging
import time:      1227 |       1227 |         packaging._structures
import time:       694 |        694 |         packaging._typing
import time:      4373 |       6293 |       packaging.version
import time:        51 |         51 |               _opcode
import time:       841 |        891 |             opcode
import time:      1088 |       1979 |           dis
import time:       784 |        784 |             importlib
import time:      1205 |       1988 |           importlib.machinery
import time:      2273 |       6239 |         inspect
import time:      1177 |       7416 |       pint.numpy_func
import time:      2930 |      28720 |     pint.quantity
import time:       984 |      29703 |   pint.measurement
import time:       637 |        637 |     pint.registry_helpers
import time:      1377 |       1377 |     pint.systems
import time:       615 |        615 |             posixpath
import time:       836 |       1450 |           fnmatch
import time:        79 |         79 |           errno
import time:       108 |        108 |           zlib
import time:       742 |        742 |             _compression
import time:       993 |        993 |             _bz2
import time:      1251 |       2985 |           bz2
import time:       915 |        915 |             _lzma
import time:      1146 |       2061 |           lzma
import time:       481 |        481 |           pwd
import time:       441 |        441 |           grp
import time:      1877 |       9478 |         shutil
import time:        76 |         76 |           _sha512
import time:       117 |        117 |           _random
import time:      1442 |       1635 |         random
import time:      1184 |      12296 |       tempfile
import time:       948 |        948 |       importlib.abc
import time:       681 |        681 |           urllib
import time:      1627 |       2308 |         urllib.parse
import time:      1490 |       3798 |       pathlib
import time:      1411 |      18452 |     importlib.resources
import time:      1807 |      22272 |   pint.registry
import time:       731 |        731 |   pint.unit
import time:       107 |        107 |       _csv
import time:      1070 |       1176 |     csv
import time:       812 |        812 |     email
import time:        96 |         96 |       binascii
import time:       830 |        830 |       importlib.util
import time:        99 |         99 |         _struct
import time:      1072 |       1171 |       struct
import time:      1919 |       4014 |     zipfile
import time:      2373 |       2373 |     configparser
import time:      1999 |      10373 |   importlib.metadata
import time:      1075 |       1075 |       email.errors
import time:       676 |        676 |           email.quoprimime
import time:       817 |        817 |             base64
import time:       744 |       1561 |           email.base64mime
import time:       651 |        651 |               quopri
import time:       787 |       1437 |             email.encoders
import time:       957 |       2393 |           email.charset
import time:      1668 |       6297 |         email.header
import time:      1958 |       1958 |             _socket
import time:       881 |        881 |               select
import time:      2158 |       3039 |             selectors
import time:      1954 |       6950 |           socket
import time:       851 |        851 |             calendar
import time:       950 |       1800 |           email._parseaddr
import time:      1465 |      10214 |         email.utils
import time:      1166 |      17676 |       email._policybase
import time:      1713 |      20462 |     email.feedparser
import time:       962 |      21424 |   email.parser
import time:       645 |        645 |     uu
import time:       715 |        715 |     email._encoded_words
import time:       517 |        517 |     email.iterators
import time:      1372 |       3248 |   email.message
import time:      4433 |     144048 | pint
```

</p>
</details>

Benchmarking the import command :

With numpy:
```
Benchmark #1: python import-pint.py 
    Time (mean ± σ):     269.8 ms ±   4.1 ms    [User: 2.7 ms, System: 9.5 ms]
    Range (min … max):   262.7 ms … 284.3 ms    100 runs
```

Without numpy:
```
Benchmark #1: python import-pint.py
    Time (mean ± σ):     156.3 ms ±   6.8 ms    [User: 3.4 ms, System: 8.9 ms]
    Range (min … max):   145.1 ms … 180.3 ms    100 runs
```

Without numpy & importlib.meta:
```
Benchmark #1: python import-pint.py
    Time (mean ± σ):     122.4 ms ±   2.3 ms    [User: 3.0 ms, System: 9.2 ms]
    Range (min … max):   118.5 ms … 131.8 ms    100 run
```

Deleting importlib.meta will just save you 30ms.
If startup time is critical, try to make pint import lazy which will import pint only when necessary in your program.

**Comment by jules-ch** [comment] 2021-07-19 18:19
I'm closing this feel free to reopen if the answer is not clear

**Closed by jules-ch** 2021-07-19 18:19 UTC
