### ISSUE TITLE
String 'nmi' interpreted as nanomile, not nautical mile

### ISSUE THREAD

**Issue by iamthad** [hgrecco/pint#391] opened 2016-06-16 22:35 UTC
Nautical mile is defined as follows in the default_en.txt:
`nautical_mile = 1852 m = nmi # exact`

But, the alias doesn't work in practice:

```
>>> import pint
>>> units = pint.UnitRegistry()
>>> units['nmi']
<Quantity(1, 'nanomile')>
```

**Comment by whoburg** [comment] 2016-09-05 19:46
duplicate of #366

**Comment by hgrecco** [comment] 2016-11-17 05:45
In #366 we fixed inline comment. Now we have to discussed how to interpret `nmi`. I think we need to remove the alias unless somebody has a better idea.

**Comment by whoburg** [comment] 2016-11-18 01:53
If the debate is between interpreting as nautical miles vs interpreting as nanomiles, I'd argue strongly for nautical miles. Nautical miles are a unit used all over the word; a nanomile is a pretty strange unit of length (about 1.61 microns, as it turns out) -- I haven't personally met anyone who works with nanomiles regularly.

According to https://en.wikipedia.org/wiki/Nautical_mile, M, NM, nm, and nmi can all be used to represent nautical miles. nmi and NM seem least ambiguous in my opinion.

**Comment by iamthad** [comment] 2016-11-18 02:00
I'd argue that any explicit alias should take precedence over a prefix + unit.

**Comment by hgrecco** [comment] 2016-11-18 04:01
Sounds a good reasoning. How shall we implement it during parsing:
1.- Drop silently the nanomile case
2.- Issue a warning
3.- Other?

**Comment by whoburg** [comment] 2016-11-18 05:11
I vote for option 1.

**Comment by onealj** [comment] 2016-11-18 05:34
If aliases have higher precedence than prefix+unit, as @iamthad proposed, then #454 could actually be implemented, though would require adding aliases for MCF, CCF. M and C could not be recognized as prefixes (if they did, they would not be interpreted as long scale prefixes).

I agree with the alias > prefix+unit order of precedence. This means 'nmi' would never be interpreted as nanomile as long as the 'nmi' nautical mile alias is defined.

Any unit test for this would need to include knmi, which I assume would be interpreted as (prefix='k', unit='nmi') = 1000 nautical miles.

**Closed** 2019-12-03 19:03 UTC
