### ISSUE TITLE
np.isfinite() changes internal type?

### ISSUE THREAD

**Issue by dopplershift** [hgrecco/pint#481] opened 2017-02-28 20:03 UTC
I have no idea what's going on here:
```python
import numpy as np
from pint import UnitRegistry
ureg = UnitRegistry()
a = np.arange(2.)
au = a * ureg.m

# Numpy Arrays
print('Numpy (base):', [type(v) for v in a])
print('Numpy (isfinite):', [type(v) for v in a if np.isfinite(v)])

# Quantity
print('Pint (base):', [type(v.magnitude) for v in au]) # ok
print('Pint (isfinite):', [type(v.magnitude) for v in au if np.isfinite(v)]) # Huh?
```
Outputs:
```
Numpy (base): [<class 'numpy.float64'>, <class 'numpy.float64'>]
Numpy (isfinite): [<class 'numpy.float64'>, <class 'numpy.float64'>]
Pint (base): [<class 'numpy.float64'>, <class 'numpy.float64'>]
Pint (isfinite): [<class 'numpy.ndarray'>, <class 'numpy.ndarray'>]
```
Why on earth does calling a numpy function modify the Quantity *in-place*???

The reason this even matters is because this works:
```python
print([format(v, '.0f') for v in au])
```
```
['0 meter', '1 meter']
```
while this:
```python
print([format(v, '.0f') for v in au if np.isfinite(v)])
```
gives me a traceback (due to NumPy not implementing `__format__`):
```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-929696747b8d> in <module>()
----> 1 [format(v, '.0f') for v in au if np.isfinite(v)]

<ipython-input-64-929696747b8d> in <listcomp>(.0)
----> 1 [format(v, '.0f') for v in au if np.isfinite(v)]

/Users/rmay/miniconda3/envs/py35/lib/python3.5/site-packages/pint/quantity.py in __format__(self, spec)
    139             obj = self
    140         return '{0} {1}'.format(
--> 141             format(obj.magnitude, remove_custom_flags(spec)),
    142             format(obj.units, spec)).replace('\n', '')
    143 

TypeError: non-empty format string passed to object.__format__
```

**Comment by gerritholl** [comment] 2017-03-02 14:49
Related to #479 .  Probably the same cause; set a breakpoint at [`_Quantity.__getattr__`](https://github.com/hgrecco/pint/blob/master/pint/quantity.py#L1167) to verify

**Comment by hgrecco** [comment] 2017-03-31 12:50
I think you are right, this was done to enable numpy operations working transparently on Pint Quantities. The problem is, I think, that we do know *who* is asking for that attribute.

Everything is fine if:
- the semantics do not depend on the dimensionality.
- the function works on both arrays and python numbers
(this is the case for `numpy.isfinite`)

However if dimensionality is importante (like `numpy.cos`) then we need to cast in place in order to work properly.

I guess that if we remove the inplace conversion then `numpy.cos` will fail on quantities with python numbers as magnitude.

**Comment by hgrecco** [comment] 2019-12-03 20:34
Revisit after #905

**Comment by keewis** [comment] 2019-12-22 22:33
I can't reproduce this on a current master. Maybe #905 fixed this?

**Comment by hgrecco** [comment] 2019-12-23 21:23
> We could wait on #925 before we close this, though.

I would rather add a test and close this issue. A test will always make us remember

**Comment by keewis** [comment] 2019-12-23 21:55
> I would rather add a test and close this issue. A test will always make us remember

... which is what #925 is about. I only realized this after posting, though

**Comment by hgrecco** [comment] 2019-12-24 18:37
:-D Indeed. I am closing this as I am trying to keep the Issue Tracker free of polution (which good but not perfect yet results)

**Comment by jthielen** [comment] 2019-12-24 20:50
> :-D Indeed. I am closing this as I am trying to keep the Issue Tracker free of polution (which good but not perfect yet results)

With that in mind, would you also want to close #509, #622, and #678, which are all in a similar position to this issue?

**Comment by hgrecco** [comment] 2019-12-24 21:02
Thanks for pointing this out!

**Closed** 2019-12-27 03:46 UTC
Labels: numpy
