### ISSUE TITLE
Custom formatters not working with modifiers (Undocumented breaking change in 0.24)

### ISSUE THREAD

**Issue by ManuelHu** [hgrecco/pint#2017] opened 2024-06-20 12:45 UTC
Combining a custom format registered with `@pint.register_unit_format` and a modifier does not work on 0.24 any more. Apparently the formatter is **silently** _not even called_.

```python3
import pint

ureg = pint.get_application_registry().get()

@pint.register_unit_format("test")
def _test_format(unit, registry, **options):
    print("format called")
    proc = {u.replace("µ", "u"): e for u, e in unit.items()}
    fmt = pint.formatting if hasattr(pint, "formatting") else pint
    return fmt.formatter(
        proc.items(),
        as_ratio=True,
        single_denominator=False,
        product_fmt="*",
        division_fmt="/",
        power_fmt="{}{}",
        parentheses_fmt="({})",
        **options,
    )

base_unit = ureg.microsecond
print(f"with modifier - {base_unit:~test}")
print(f"without modifier - {base_unit:test}")
```

### Output on pint 0.23
```
format called
with modifier - us
format called
without modifier - microsecond

```

### Output on pint 0.24
```
with modifier - µs
format called
without modifier - microsecond
```
---
unfortunately we currently have to still support python 3.9, so only supporting pint 0.24+ is not an option for us, our code has to work on both versions... :-(

**Comment by hgrecco** [comment] 2024-06-20 13:43
I think this is the same problem that is fixed in #2011

**Comment by ManuelHu** [comment] 2024-06-20 14:12
I tried to apply that patch locally, and it does not work.

For more debuggin I added a print statement like this:
```diff
     def get_formatter(self, spec: str):
         if spec == "":
             return self._formatters["D"]
         for k, v in self._formatters.items():
             if k in spec:
                 return v
+        print(spec)
         try:
             orphan_fmt = REGISTERED_FORMATTERS[spec]
         except KeyError:
             return self._formatters["D"]
```

which gives a spec of `~test` in my testcase above. And that format spec is certainly not defined, as it still contains the `~` modifier.

**Comment by hgrecco** [comment] 2024-06-21 01:40
The problem is that is returning an orphan formatter (i.e. one not attached to the registry)

Try replacing:
```python
        try:
            orphan_fmt = REGISTERED_FORMATTERS[spec]
        except KeyError:
            return self._formatters["D"]
```

by 

```python
        for k, v in REGISTERED_FORMATTERS.items():
            if k in spec:
                orphan_fmt = REGISTERED_FORMATTERS[spec]
                break
        else:
            return self._formatters["D"]
```

Please notice that the check is: `if k in spec:`. That means that if `k == test` and `spec == ~test` this should return the right formatter. 

If it works, please submit a PR linking to @2011 ping: @andrewgsavage

**Closed** 2024-06-21 15:35 UTC

**Comment by andrewgsavage** [comment] 2024-06-21 15:36
should be working now
