### ISSUE TITLE
Using pint inside IPython widgets

### ISSUE THREAD

**Issue by whoburg** [hgrecco/pint#284] opened 2015-07-15 15:13 UTC
This likely belongs over at IPython, but I thought I should raise it here first.

This is a simple example from the [IPython documentation](http://ipython.org/ipython-doc/3/api/generated/IPython.html.widgets.interaction.html), but modified to try to use a pint `Quantity` as the value in a slider widget. This should be run in an IPython notebook:

```python
from IPython.html.widgets.interaction import interact
import pint
@interact
def square(num=2*pint.UnitRegistry()('m')):
    print "{} times 2 is {}".format(num, num*2)
```
If one replaces `num=2*pint.UnitRegistry()('m')` with `num=2`, everything works. But with the `Quantity` there, 
```python

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-821ca95d6590> in <module>()
      2 import pint
      3 @interact
----> 4 def square(num=2*pint.UnitRegistry()('m')):
      5     print "{} times 2 is {}".format(num, num*2)

.../lib/python2.7/site-packages/IPython/html/widgets/interaction.pyc in interact(__interact_f, **kwargs)
    308         #        ...
    309         f = __interact_f
--> 310         w = interactive(f, **kwargs)
    311         try:
    312             f.widget = w

.../lib/python2.7/site-packages/IPython/html/widgets/interaction.pyc in interactive(__interact_f, **kwargs)
    194     getcallargs(f, **{n:v for n,v,_ in new_kwargs})
    195     # Now build the widgets from the abbreviations.
--> 196     kwargs_widgets.extend(_widgets_from_abbreviations(new_kwargs))
    197 
    198     # This has to be done as an assignment, not using container.children.append,

.../lib/python2.7/site-packages/IPython/html/widgets/interaction.pyc in _widgets_from_abbreviations(seq)
    153     result = []
    154     for name, abbrev, default in seq:
--> 155         widget = _widget_from_abbrev(abbrev, default)
    156         if not widget.description:
    157             widget.description = name

.../lib/python2.7/site-packages/IPython/html/widgets/interaction.pyc in _widget_from_abbrev(abbrev, default)
    113             pass
    114     if widget is None:
--> 115         raise ValueError("%r cannot be transformed to a Widget" % (abbrev,))
    116     return widget
    117 

ValueError: <Quantity(2, 'meter')> cannot be transformed to a Widget
```

**Comment by hgrecco** [comment] 2015-07-16 20:41
It is not a bug of IPython nor a bug in Pint. It is just how the IPython widget's work. When you do say `num=2`, IPython detects that is a number and creates a range of possible values. You could achieve something like this with a Selection Widget (ie. you specify the a list of quantities yourself) or with:

```python
from IPython.html.widgets.interaction import interact
import pint
ureg = pint.UnitRegistry()

@interact
def square(num=2):
    num = num * ureg.meter
    q = 2 * num
    print("{} times 2 is {}".format(num, num*2))
```

**Comment by whoburg** [comment] 2015-07-18 15:13
Clarification: the functionality I'm looking for is for the units to be displayed next to the slider itself, where IPython currently prints a number. Often a widget has many sliders and it could be helpful for users to know the units of the sliders they are controlling. I can't simply print the units in my interact function because that displays information far away from the slider (and IPython is already printing a number next to the slider).

@hgrecco does your proposal above address this? I would be willing to specify a list of Quantity objects for the slider -- but I don't think that functionality works on the IPython side. The Selection Widget seems much more awkward than a slider for real-valued quantities with units.

**Comment by hgrecco** [comment] 2015-07-19 04:03
I do not think this is possible with IPython and Pint as IPython widget does not define any protocol that Pint can implement. But you could implement your own IPython Widget that is Pint aware subclassing the SliderWidget

**Comment by hgrecco** [comment] 2015-12-22 03:24
I am closing this right now, feel free to reopen if needed or if you find an API that we can implement.

**Closed by hgrecco** 2015-12-22 03:24 UTC
