### ISSUE TITLE
siunitx formatter

### ISSUE THREAD

**Issue by productivememberofsociety666** [hgrecco/pint#200] opened 2014-10-19 01:14 UTC
It would be neat if you could output units in [siunitx](http://mirrors.ctan.org/macros/latex/contrib/siunitx/siunitx.pdf) format as well. Much more readable than manually formatted LaTeX units.

**Comment by CD3** [comment] 2015-09-20 13:50
I am very interested in this feature. I am using python scripts to generate LaTeX documents for homework assignments, and the default LaTeX formatted does not work for this. The generated string must be wrapped in math mode for fractions and powers, but this causes the units to be italicized. siunitx is a great packages that handles the unit formatting correctly in both math and non-math modes.

**Comment by CD3** [comment] 2015-11-20 20:31
I am going to take a cut at implementing @productivememberofsociety666 's solution in the __format__ method. I don't think it is necessary to try and implement all of siunitx configuration options, you could just allow the format string to take raw text to put in the options box. For example

```
'{:.3o[per-mode=fraction]LX}'.format(q)
```
If the user wants the a common option for all strings, they can just call the `\sisetup` in the document they are generating.

**Comment by productivememberofsociety666** [comment] 2015-12-07 20:31
Sorry, I didn't live up to my username on this one :grimacing:

@CD3's proposal sounds reasonable, I'll be sure to try it and see if I run into any problems.

**Comment by CD3** [comment] 2015-12-07 21:35
It turns out that it will not be as straight forward to add as I had originally thought. It does not integrate well into the unit formatting framework in currently `pint` (in `formatting.py`). The issue is that `pint` formats the magnitude and units separately and the functions in `formatting.py` just handle the formatting of units. An `siunitx` formatter needs access to bot the magnitude and unit of a quantity in order to put them into an `\SI{mag}{unit}` command.

So, the `__format__` functions in the `quantity` and `measurement` classes (and probably the `unit` class as well) need to be modified to handle this as a special case. I am currently using a monkey patch and have been testing for about a month now without problems.

I will be happy to integrate this into the library and submit a PR if @hgrecco is interested.

**Comment by hgrecco** [comment] 2015-12-09 15:47
Looks good to me. Thanks!. I will merge it during the weekend. But before that, I was wondering if we can replace the formatting code for a single letter (Maybe just `X`, but I am open to others). I think that follows the rationale of the other formatting codes. Opinions?

**Comment by CD3** [comment] 2015-12-09 16:05
I debated on that, and I finally decided on `Lx` because I wanted to indicate that it is a LaTeX formatter. After digging into how the `__format__` function and formatting codes work, I actually think it makes sense now. The `x` is a modifier to the `L` format code. Since you can chain formatting codes, all of the `pint` codes essentially work this way. `{:.2EL}` says to output in exponential format, modified for LaTeX.

The uncertainties module has a similar code, `u`, which allows you to control the number of significant figures you want on the uncertainty, so `{:.2uELx}` says to print the measurement with the uncertainty to 2 significant figure, in exponential format, in LaTex, for the siunitx package.

That said, if you want a single format code, it makes no difference to me. I will change it and resubmit after we decide.

**Comment by hgrecco** [comment] 2015-12-09 16:07
Sounds reasonable to me. I will merge it on the weekend so let's anyway leave a couple more days to hear more opinions (if any). Thanks again!

**Comment by CD3** [comment] 2015-12-09 16:09
Sounds good. Thanks. And thanks for the library, this has been extremely useful to me.

**Comment by productivememberofsociety666** [comment] 2015-12-11 16:36
Looks good to me, thanks for fixing this @CD3!

**Comment by hgrecco** [comment] 2015-12-22 03:41
Merged already

**Closed by hgrecco** 2015-12-22 03:41 UTC
